name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn run eslint . --ext .js,.jsx,.ts,.tsx

      - name: Build IOS
        run: yarn run react-native run-ios --simulator="iPhone 12"

      - name: Build Android
        run: cd android && chmod +x gradlew && ./gradlew assembleRelease
