name: CI

on: pull_request

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn run eslint . --ext .js,.jsx,.ts,.tsx

      - name: Build IOS
        run: yarn run react-native run-ios

      - name: Build Android
        run: cd android && chmod +x gradlew && ./gradlew assembleRelease
