name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn run eslint . --ext .js,.jsx,.ts,.tsx

      - name: Build IOS
        run: yarn run react-native run-ios

      - name: Build Android
        run: react-native run-android
