name: CI

on: pull_request

jobs:
  build:
    runs-on: macos-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Lint
        run: yarn run eslint . --ext .js,.jsx,.ts,.tsx

      - name: Install iOS pod dependencies 
        run: pod install
        working-directory: ios

      - name: Build iOS
        run: yarn run react-native run-ios

      - name: Build Android
        run: cd android && chmod +x gradlew && ./gradlew assembleRelease
